2017-07-20 23:41:17.774 [error] <0.168.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.173.0> exit with reason normal in context child_terminated
2017-07-20 23:41:17.804 [info] <0.33.0> Application lager started on node nonode@nohost
2017-07-20 23:41:17.808 [info] <0.33.0> Application gpb started on node nonode@nohost
2017-07-20 23:41:17.808 [info] <0.33.0> Application exprotobuf started on node nonode@nohost
2017-07-20 23:41:17.813 [info] <0.33.0> Application hpack started on node nonode@nohost
2017-07-20 23:41:17.813 [info] <0.33.0> Application chatterbox started on node nonode@nohost
2017-07-20 23:41:17.817 [info] <0.33.0> Application cowlib started on node nonode@nohost
2017-07-20 23:41:17.824 [info] <0.33.0> Application ranch started on node nonode@nohost
2017-07-20 23:41:17.829 [info] <0.33.0> Application cowboy started on node nonode@nohost
2017-07-20 23:41:17.829 [info] <0.33.0> Application grpc started on node nonode@nohost
2017-07-20 23:41:17.836 [error] <0.222.0> CRASH REPORT Process <0.222.0> with 0 neighbours exited with reason: call to undefined function 'Elixir.Plug.Adapters.Cowboy':child_spec(http, 'Elixir.ExAddy.Router', [], [{port,4000}]) in application_master:init/4 line 134
2017-07-20 23:42:52.534 [error] <0.176.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.181.0> exit with reason normal in context child_terminated
2017-07-20 23:42:52.562 [info] <0.33.0> Application lager started on node nonode@nohost
2017-07-20 23:42:52.567 [info] <0.33.0> Application gpb started on node nonode@nohost
2017-07-20 23:42:52.567 [info] <0.33.0> Application exprotobuf started on node nonode@nohost
2017-07-20 23:42:52.570 [info] <0.33.0> Application hpack started on node nonode@nohost
2017-07-20 23:42:52.570 [info] <0.33.0> Application chatterbox started on node nonode@nohost
2017-07-20 23:42:52.572 [info] <0.33.0> Application cowlib started on node nonode@nohost
2017-07-20 23:42:52.586 [info] <0.33.0> Application ranch started on node nonode@nohost
2017-07-20 23:42:52.591 [info] <0.33.0> Application cowboy started on node nonode@nohost
2017-07-20 23:42:52.591 [info] <0.33.0> Application grpc started on node nonode@nohost
2017-07-20 23:42:52.591 [info] <0.33.0> Application ex_addy started on node nonode@nohost
2017-07-20 23:43:27.095 [error] <0.238.0> Failed to start Ranch listener 'Elixir.Addy.Adder.Server' in ranch_tcp:listen([{port,50051}]) for reason eaddrinuse (address already in use)
2017-07-20 23:43:27.095 [error] <0.238.0> CRASH REPORT Process <0.238.0> with 0 neighbours exited with reason: {listen_error,'Elixir.Addy.Adder.Server',eaddrinuse} in ranch_acceptors_sup:listen_error/4 line 56
2017-07-20 23:43:27.095 [error] <0.236.0> Supervisor {<0.236.0>,ranch_listener_sup} had child ranch_acceptors_sup started with ranch_acceptors_sup:start_link('Elixir.Addy.Adder.Server', 100, ranch_tcp, [{connection_type,supervisor},{port,50051}]) at undefined exit with reason {listen_error,'Elixir.Addy.Adder.Server',eaddrinuse} in context start_error
2017-07-20 23:43:53.222 [warning] <0.32.0> lager_error_logger_h dropped 24 messages in the last second that exceeded the limit of 50 messages/sec
2017-07-20 23:47:02.595 [info] <0.345.0>@h2_connection:route_frame:545 [client] Stream 1 WindowUpdate 7
2017-07-20 23:47:14.452 [info] <0.345.0>@h2_connection:route_frame:545 [client] Stream 3 WindowUpdate 7
2017-07-20 23:47:15.486 [info] <0.345.0>@h2_connection:route_frame:545 [client] Stream 5 WindowUpdate 7
2017-07-20 23:47:16.494 [info] <0.345.0>@h2_connection:route_frame:545 [client] Stream 7 WindowUpdate 7
