2017-07-20 23:41:17.774 [error] <0.168.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.173.0> exit with reason normal in context child_terminated
2017-07-20 23:41:17.836 [error] <0.222.0> CRASH REPORT Process <0.222.0> with 0 neighbours exited with reason: call to undefined function 'Elixir.Plug.Adapters.Cowboy':child_spec(http, 'Elixir.ExAddy.Router', [], [{port,4000}]) in application_master:init/4 line 134
2017-07-20 23:42:52.534 [error] <0.176.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.181.0> exit with reason normal in context child_terminated
2017-07-20 23:43:27.095 [error] <0.238.0> Failed to start Ranch listener 'Elixir.Addy.Adder.Server' in ranch_tcp:listen([{port,50051}]) for reason eaddrinuse (address already in use)
2017-07-20 23:43:27.095 [error] <0.238.0> CRASH REPORT Process <0.238.0> with 0 neighbours exited with reason: {listen_error,'Elixir.Addy.Adder.Server',eaddrinuse} in ranch_acceptors_sup:listen_error/4 line 56
2017-07-20 23:43:27.095 [error] <0.236.0> Supervisor {<0.236.0>,ranch_listener_sup} had child ranch_acceptors_sup started with ranch_acceptors_sup:start_link('Elixir.Addy.Adder.Server', 100, ranch_tcp, [{connection_type,supervisor},{port,50051}]) at undefined exit with reason {listen_error,'Elixir.Addy.Adder.Server',eaddrinuse} in context start_error
